<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-25 08:32
=======
# Generated by Django 3.2.8 on 2021-10-28 06:51
>>>>>>> af6a9cf2b0bf30d3186e3d7555bee2131c53e321

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copname', models.CharField(max_length=30, unique=True, verbose_name='公司名称')),
                ('copinfo', models.TextField(default='', verbose_name='公司简介')),
<<<<<<< HEAD
                ('creditlevel', models.TextField(default='', verbose_name='信用水平')),
                ('industry', models.TextField(default='', verbose_name='行业')),
                ('solvency', models.TextField(default='', verbose_name='solvency')),
                ('profitmargin', models.TextField(default='', verbose_name='profitmargin')),
                ('incomegrowth', models.TextField(default='', verbose_name='incomegrowth')),
                ('profitgrowth', models.TextField(default='', verbose_name='profitgrowth')),
                ('cashdebt', models.TextField(default='', verbose_name='cashdebt')),
                ('cashflowdebt', models.TextField(default='', verbose_name='cashflowdebt')),
                ('turnoverrate', models.TextField(default='', verbose_name='turnoverrate')),
                ('debtratio', models.TextField(default='', verbose_name='debtratio')),
                ('roegrowth', models.TextField(default='', verbose_name='roegrowth')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.TextField(default='', verbose_name='行业')),
                ('solvency', models.FloatField(default='', verbose_name='solvency')),
                ('profitmargin', models.FloatField(default='', verbose_name='profitmargin')),
                ('incomegrowth', models.FloatField(default='', verbose_name='incomegrowth')),
                ('profitgrowth', models.FloatField(default='', verbose_name='profitgrowth')),
                ('cashdebt', models.FloatField(default='', verbose_name='cashdebt')),
                ('cashflowdebt', models.FloatField(default='', verbose_name='cashflowdebt')),
                ('turnoverrate', models.FloatField(default='', verbose_name='turnoverrate')),
                ('debtratio', models.FloatField(default='', verbose_name='debtratio')),
                ('roegrowth', models.FloatField(default='', verbose_name='roegrowth')),
=======
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
>>>>>>> af6a9cf2b0bf30d3186e3d7555bee2131c53e321
            ],
        ),
    ]
