# Generated by Django 3.2.9 on 2021-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ltd', models.FloatField(default='', verbose_name='Ltd')),
                ('EBITDA', models.FloatField(default='', verbose_name='EBITDA')),
                ('Cag', models.FloatField(default='', verbose_name='Cag')),
                ('Pol', models.FloatField(default='', verbose_name='Pol')),
                ('Roe', models.FloatField(default='', verbose_name='Roe')),
                ('Se', models.FloatField(default='', verbose_name='Se')),
                ('OP', models.FloatField(default='', verbose_name='OP')),
                ('It', models.FloatField(default='', verbose_name='It')),
                ('Cat', models.FloatField(default='', verbose_name='Cat')),
                ('Ncf', models.FloatField(default='', verbose_name='Ncf')),
                ('Ibd', models.FloatField(default='', verbose_name='Ibd')),
                ('Alr', models.FloatField(default='', verbose_name='Alr')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('result', models.TextField(default='', verbose_name='result')),
                ('username', models.TextField(default='', verbose_name='username')),
            ],
        ),
    ]
